name: Deploy Zola to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/gh-pages'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Abridge theme

      - name: Install and Build Zola
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
